language: python
python:
  - 3.8

env:
  - SECRET_KEY=secretkey

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - mypy .
  - flake8
  - pytest --cov-report=xml --cov-config=.coveragerc --cov=. -n auto

after_success:
  - codecov